# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-cf3c791b-2f4e-46ec-a1b5-af009b3cbd51";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-cf3c791b-2f4e-46ec-a1b5-af009b3cbd51".device = "/dev/disk/by-uuid/cf3c791b-2f4e-46ec-a1b5-af009b3cbd51";

  # /bin and /usr/bin are managed by services.envfs (FUSE). The old bind mount
  # here conflicted with envfs's usr-bin.mount and caused shutdown/boot errors.

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2607-E88B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
